apiVersion: v1
kind: Config
clusters:
- name: "hw2-cluster"
  cluster:
    server: "https://ec2-44-204-162-251.compute-1.amazonaws.com/k8s/clusters/c-m-4wm4b77f"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2akNDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk0T1RNeApNakk1T1RBZUZ3MHlNekEzTVRRd05USTBOVGxhRncwek16QTNNVEV3TlRJME5UbGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qZzVNekV5TWprNU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRWVvbTVncy9DOG9HbgpSVmdOMzN5bEEwK1k2QlkzQ0tmWEkyNU1SU\
      zFvdmVjblVIeUhCTGhBVExGRGdrNnpzcDFuNVZvMjgvbFBNYURoCjlzK2c2UWp1RzZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGR\
      XA2SDVJQjJTbyt5cG5WNDV2eVU2NjRrdGZ4TUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFEKwpuR\
      WcyVjNQNjVzRTlLN0ZETUlmRFFRcmlrNzVqTjhQR2RqNkVyWE4rb0FJaEFQeUV6emRNaGY2czlsS\
      FFoMmJiCklvRE1ETlFmSDNwU1lmOHc3aEl4ZWFmNgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "hw2-cluster"
  user:
    token: "kubeconfig-user-94k8gnm9s4:xr8spcxvhqsw7v7mvh7g2bgjvnsr8rqk24jrf8zrgw4rbv6ngt248k"


contexts:
- name: "hw2-cluster"
  context:
    user: "hw2-cluster"
    cluster: "hw2-cluster"

current-context: "hw2-cluster"
