apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.9.162"],"port":30252,"protocol":"TCP","serviceName":"default:hw2-cluster-deployment-nodeport","allNodes":true}]
    field.cattle.io/targetWorkloadIds: '["default/hw2-cluster-deployment"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2023-07-11T02:30:35Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d9b90504-fbd9-4320-881c-488457c17e08"}: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2023-07-11T02:30:35Z'
  name: hw2-cluster-deployment-nodeport
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: hw2-cluster-deployment
      uid: d9b90504-fbd9-4320-881c-488457c17e08
  resourceVersion: '3845'
  uid: a57be710-8b34-4848-822b-481d70b317d6
spec:
  clusterIP: 10.43.145.241
  clusterIPs:
    - 10.43.145.241
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nodeport
      nodePort: 30252
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-hw2-cluster-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
