apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-gq8wb
  creationTimestamp: '2023-07-11T02:23:26Z'
  finalizers:
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
    - wrangler.cattle.io/cloud-config-secret-remover
  generation: 2
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-calico: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machinePoolDefaults: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2023-07-11T02:23:27Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
      manager: rancher-v2.7.5-secret-migrator
      operation: Update
      time: '2023-07-11T02:23:29Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2023-07-11T02:28:37Z'
  name: hw2-cluster
  namespace: fleet-default
  resourceVersion: '6430'
  uid: 20ff65d1-bcc3-4ad8-91c7-54dcaf5edaec
spec:
  kubernetesVersion: v1.26.6+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: hw2-cluster-kubeconfig
  clusterName: c-m-8x9frcvg
  conditions:
    - lastUpdateTime: '2023-07-11T02:28:08Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-07-11T02:23:26Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-07-11T02:28:23Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2023-07-11T02:28:37Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2023-07-11T02:23:27Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2023-07-11T02:23:27Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2023-07-11T02:23:27Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2023-07-11T02:23:28Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2023-07-11T02:23:32Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2023-07-11T02:28:25Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2023-07-11T02:28:25Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2023-07-11T02:28:37Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2023-07-11T02:23:33Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2023-07-11T02:23:33Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2023-07-11T02:23:33Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2023-07-11T02:23:33Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2023-07-11T02:23:34Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2023-07-11T02:23:34Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2023-07-11T02:28:23Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2023-07-11T02:27:42Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2023-07-11T02:28:07Z'
      status: 'True'
      type: Waiting
    - lastUpdateTime: '2023-07-11T02:28:16Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2023-07-11T02:28:19Z'
      status: 'True'
      type: AgentDeployed
  observedGeneration: 2
  ready: true
