apiVersion: v1
kind: Config
clusters:
- name: "hw2-cluster"
  cluster:
    server: "https://ec2-44-199-191-33.compute-1.amazonaws.com/k8s/clusters/c-m-kshtkc78"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2akNDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      Fk0T1RFeQpOek0wT0RBZUZ3MHlNekEzTVRJd01qQXlNamhhRncwek16QTNNRGt3TWpBeU1qaGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qZzVNVEkzTXpRNE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRVhTdEtKdFZRUHdERgpNandaOHRvUzFzQWs4Y0tldENBVzFJRWgvM\
      GNEZk9xcFBjOWdZWmtLdkFlaDJJWnVVdUVJZmlRWEhDelViVjF1CmZOa0dBSDYza3FOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQ\
      UliVHlwQmh0a3hSMERsWkFVc0c4YzRjaUFNTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFEdgowM\
      WJSTU8rdmJTRDZDdW5KVjRHMDZqSnVMdjRraWxITW5VQi84eWk3SndJaEFNdjF4a0pLZ0ZsUE82b\
      npDbWh3Cmt0cmhKL1o4QjRHVnluc2ljcEx4SFRVMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "hw2-cluster"
  user:
    token: "kubeconfig-user-cg57wpxllc:4jbbcxdncqszrd8d6m9gvftpqp7k7p57qt94qhdc74p2tzgtgnh6kl"


contexts:
- name: "hw2-cluster"
  context:
    user: "hw2-cluster"
    cluster: "hw2-cluster"

current-context: "hw2-cluster"

